// Generated by gencpp from file mavros_msgs/AttitudeThrustTarget.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_ATTITUDETHRUSTTARGET_H
#define MAVROS_MSGS_MESSAGE_ATTITUDETHRUSTTARGET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Quaternion.h>
#include <geometry_msgs/Vector3.h>

namespace mavros_msgs
{
template <class ContainerAllocator>
struct AttitudeThrustTarget_
{
  typedef AttitudeThrustTarget_<ContainerAllocator> Type;

  AttitudeThrustTarget_()
    : header()
    , linear_acceleration()
    , angular_acceleration()
    , orientation()
    , rates_sp()  {
    }
  AttitudeThrustTarget_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , linear_acceleration(_alloc)
    , angular_acceleration(_alloc)
    , orientation(_alloc)
    , rates_sp(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _linear_acceleration_type;
  _linear_acceleration_type linear_acceleration;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _angular_acceleration_type;
  _angular_acceleration_type angular_acceleration;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _rates_sp_type;
  _rates_sp_type rates_sp;





  typedef boost::shared_ptr< ::mavros_msgs::AttitudeThrustTarget_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavros_msgs::AttitudeThrustTarget_<ContainerAllocator> const> ConstPtr;

}; // struct AttitudeThrustTarget_

typedef ::mavros_msgs::AttitudeThrustTarget_<std::allocator<void> > AttitudeThrustTarget;

typedef boost::shared_ptr< ::mavros_msgs::AttitudeThrustTarget > AttitudeThrustTargetPtr;
typedef boost::shared_ptr< ::mavros_msgs::AttitudeThrustTarget const> AttitudeThrustTargetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavros_msgs::AttitudeThrustTarget_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavros_msgs::AttitudeThrustTarget_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mavros_msgs::AttitudeThrustTarget_<ContainerAllocator1> & lhs, const ::mavros_msgs::AttitudeThrustTarget_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.linear_acceleration == rhs.linear_acceleration &&
    lhs.angular_acceleration == rhs.angular_acceleration &&
    lhs.orientation == rhs.orientation &&
    lhs.rates_sp == rhs.rates_sp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mavros_msgs::AttitudeThrustTarget_<ContainerAllocator1> & lhs, const ::mavros_msgs::AttitudeThrustTarget_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mavros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::AttitudeThrustTarget_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::AttitudeThrustTarget_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::AttitudeThrustTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::AttitudeThrustTarget_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::AttitudeThrustTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::AttitudeThrustTarget_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavros_msgs::AttitudeThrustTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "577effa78ecf2228b3b93dbb5688d88f";
  }

  static const char* value(const ::mavros_msgs::AttitudeThrustTarget_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x577effa78ecf2228ULL;
  static const uint64_t static_value2 = 0xb3b93dbb5688d88fULL;
};

template<class ContainerAllocator>
struct DataType< ::mavros_msgs::AttitudeThrustTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavros_msgs/AttitudeThrustTarget";
  }

  static const char* value(const ::mavros_msgs::AttitudeThrustTarget_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavros_msgs::AttitudeThrustTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message for SET_WRENCH_TARGET_BODY_NED\n"
"#\n"
"\n"
"std_msgs/Header header\n"
"\n"
"geometry_msgs/Vector3 linear_acceleration\n"
"geometry_msgs/Vector3 angular_acceleration\n"
"geometry_msgs/Quaternion orientation\n"
"geometry_msgs/Vector3 rates_sp\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::mavros_msgs::AttitudeThrustTarget_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavros_msgs::AttitudeThrustTarget_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.linear_acceleration);
      stream.next(m.angular_acceleration);
      stream.next(m.orientation);
      stream.next(m.rates_sp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AttitudeThrustTarget_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavros_msgs::AttitudeThrustTarget_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavros_msgs::AttitudeThrustTarget_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "linear_acceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_acceleration);
    s << indent << "angular_acceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angular_acceleration);
    s << indent << "orientation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
    s << indent << "rates_sp: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.rates_sp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_ATTITUDETHRUSTTARGET_H
