// Generated by gencpp from file mavros_msgs/TiltAngleTarget.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_TILTANGLETARGET_H
#define MAVROS_MSGS_MESSAGE_TILTANGLETARGET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mavros_msgs
{
template <class ContainerAllocator>
struct TiltAngleTarget_
{
  typedef TiltAngleTarget_<ContainerAllocator> Type;

  TiltAngleTarget_()
    : header()
    , alpha()  {
      alpha.assign(0.0);
  }
  TiltAngleTarget_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , alpha()  {
  (void)_alloc;
      alpha.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<float, 6>  _alpha_type;
  _alpha_type alpha;





  typedef boost::shared_ptr< ::mavros_msgs::TiltAngleTarget_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavros_msgs::TiltAngleTarget_<ContainerAllocator> const> ConstPtr;

}; // struct TiltAngleTarget_

typedef ::mavros_msgs::TiltAngleTarget_<std::allocator<void> > TiltAngleTarget;

typedef boost::shared_ptr< ::mavros_msgs::TiltAngleTarget > TiltAngleTargetPtr;
typedef boost::shared_ptr< ::mavros_msgs::TiltAngleTarget const> TiltAngleTargetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavros_msgs::TiltAngleTarget_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavros_msgs::TiltAngleTarget_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mavros_msgs::TiltAngleTarget_<ContainerAllocator1> & lhs, const ::mavros_msgs::TiltAngleTarget_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.alpha == rhs.alpha;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mavros_msgs::TiltAngleTarget_<ContainerAllocator1> & lhs, const ::mavros_msgs::TiltAngleTarget_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mavros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::TiltAngleTarget_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::TiltAngleTarget_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::TiltAngleTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::TiltAngleTarget_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::TiltAngleTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::TiltAngleTarget_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavros_msgs::TiltAngleTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ae6c66e45d76ecf90e91f02495c84c7a";
  }

  static const char* value(const ::mavros_msgs::TiltAngleTarget_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xae6c66e45d76ecf9ULL;
  static const uint64_t static_value2 = 0x0e91f02495c84c7aULL;
};

template<class ContainerAllocator>
struct DataType< ::mavros_msgs::TiltAngleTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavros_msgs/TiltAngleTarget";
  }

  static const char* value(const ::mavros_msgs::TiltAngleTarget_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavros_msgs::TiltAngleTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Tilt angles for overactuated vehicles\n"
"#\n"
"\n"
"std_msgs/Header header\n"
"\n"
"float32[6] alpha\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mavros_msgs::TiltAngleTarget_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavros_msgs::TiltAngleTarget_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.alpha);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TiltAngleTarget_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavros_msgs::TiltAngleTarget_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavros_msgs::TiltAngleTarget_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "alpha[]" << std::endl;
    for (size_t i = 0; i < v.alpha.size(); ++i)
    {
      s << indent << "  alpha[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.alpha[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_TILTANGLETARGET_H
