(cl:in-package mavlink_ros-msg)
(cl:export '(HEADER-VAL
          HEADER
          H-VAL
          H
          HREF-VAL
          HREF
          HREF_T-VAL
          HREF_T
          PITCHANGLE-VAL
          PITCHANGLE
          PITCHANGLEREF-VAL
          PITCHANGLEREF
          Q-VAL
          Q
          QREF-VAL
          QREF
          UELEV-VAL
          UELEV
          UTHROT-VAL
          UTHROT
          UTHROT2-VAL
          UTHROT2
          AZ-VAL
          AZ
          YAWANGLE-VAL
          YAWANGLE
          YAWANGLEREF-VAL
          YAWANGLEREF
          ROLLANGLE-VAL
          ROLLANGLE
          ROLLANGLEREF-VAL
          ROLLANGLEREF
          P-VAL
          P
          PREF-VAL
          PREF
          R-VAL
          R
          RREF-VAL
          RREF
          UAIL-VAL
          UAIL
          URUD-VAL
          URUD
          ASLCTRL_MODE-VAL
          ASLCTRL_MODE
))