(cl:in-package mavlink_ros-msg)
(cl:export '(HEADER-VAL
          HEADER
          DBARO_PRES_PA-VAL
          DBARO_PRES_PA
          DBARO_VELO_MS-VAL
          DBARO_VELO_MS
          AMB_TEMP_CELSIUS-VAL
          AMB_TEMP_CELSIUS
          ADC121_VSPB_VOLT-VAL
          ADC121_VSPB_VOLT
          ADC121_CSPB_AMP-VAL
          ADC121_CSPB_AMP
          ADC121_CS1_AMP-VAL
          ADC121_CS1_AMP
          ADC121_CS2_AMP-VAL
          ADC121_CS2_AMP
          MPPT1_VOLT-VAL
          MPPT1_VOLT
          MPPT1_AMP-VAL
          MPPT1_AMP
          MPPT2_VOLT-VAL
          MPPT2_VOLT
          MPPT2_AMP-VAL
          MPPT2_AMP
          MPPT3_VOLT-VAL
          MPPT3_VOLT
          MPPT3_AMP-VAL
          MPPT3_AMP
          MPPT1_PWM-VAL
          MPPT1_PWM
          MPPT2_PWM-VAL
          MPPT2_PWM
          MPPT3_PWM-VAL
          MPPT3_PWM
          MPPT1_STATUS-VAL
          MPPT1_STATUS
          MPPT2_STATUS-VAL
          MPPT2_STATUS
          MPPT3_STATUS-VAL
          MPPT3_STATUS
))